class Search:
    united_states = [('alabama', 'auburn'),
        ('alabama', 'bham'),
        ('alabama', 'dothan'),
        ('alabama', 'gadsden'),
        ('alabama', 'huntsville'),
        ('alabama', 'mobile'),
        ('alabama', 'montgomery'),
        ('alabama', 'shoals'),
        ('alabama', 'tuscaloosa'),
        ('alaska', 'anchorage'),
        ('alaska', 'fairbanks'),
        ('alaska', 'juneau'),
        ('alaska', 'kenai'),
        ('arizona', 'flagstaff'),
        ('arizona', 'mohave'),
        ('arizona', 'phoenix', 'cph'),
        ('arizona', 'phoenix', 'evl'),
        ('arizona', 'phoenix', 'nph'),
        ('arizona', 'phoenix', 'wvl'),
        ('arizona', 'prescott'),
        ('arizona', 'showlow'),
        ('arizona', 'sierravista'),
        ('arizona', 'tucson'),
        ('arizona', 'yuma'),
        ('arkansas', 'fayar'),
        ('arkansas', 'fortsmith'),
        ('arkansas', 'jonesboro'),
        ('arkansas', 'littlerock'),
        ('arkansas', 'texarkana'),
        ('california', 'bakersfield'),
        ('california', 'chico'),
        ('california', 'fresno'),
        ('california', 'goldcountry'),
        ('california', 'hanford'),
        ('california', 'humboldt'),
        ('california', 'imperial'),
        ('california', 'inlandempire'),
        ('california', 'losangeles', 'ant'),
        ('california', 'losangeles', 'lac'),
        ('california', 'losangeles', 'lgb'),
        ('california', 'losangeles', 'sfv'),
        ('california', 'losangeles', 'sgv'),
        ('california', 'losangeles', 'wst'),
        ('california', 'mendocino'),
        ('california', 'merced'),
        ('california', 'modesto'),
        ('california', 'monterey'),
        ('california', 'orangecounty'),
        ('california', 'palmsprings'),
        ('california', 'redding'),
        ('california', 'sacramento'),
        ('california', 'sandiego', 'csd'),
        ('california', 'sandiego', 'esd'),
        ('california', 'sandiego', 'nsd'),
        ('california', 'sandiego', 'ssd'),
        ('california', 'santabarbara'),
        ('california', 'santamaria'),
        ('california', 'sfbay', 'eby'),
        ('california', 'sfbay', 'nby'),
        ('california', 'sfbay', 'pen'),
        ('california', 'sfbay', 'sby'),
        ('california', 'sfbay', 'scz'),
        ('california', 'sfbay', 'sfc'),
        ('california', 'siskiyou'),
        ('california', 'slo'),
        ('california', 'stockton'),
        ('california', 'susanville'),
        ('california', 'ventura'),
        ('california', 'visalia'),
        ('california', 'yubasutter'),
        ('colorado', 'boulder'),
        ('colorado', 'cosprings'),
        ('colorado', 'denver'),
        ('colorado', 'eastco'),
        ('colorado', 'fortcollins'),
        ('colorado', 'pueblo'),
        ('colorado', 'rockies'),
        ('colorado', 'westslope'),
        ('connecticut', 'hartford'),
        ('connecticut', 'newhaven'),
        ('connecticut', 'newlondon'),
        ('connecticut', 'nwct'),
        ('delaware', 'delaware'),
        ('district_of_columbia', 'washingtondc'),
        ('florida', 'cfl'),
        ('florida', 'daytona'),
        ('florida', 'fortlauderdale', 'brw'),
        ('florida', 'fortlauderdale', 'mdc'),
        ('florida', 'fortlauderdale', 'pbc'),
        ('florida', 'fortmyers', 'chl'),
        ('florida', 'fortmyers', 'col'),
        ('florida', 'fortmyers', 'lee'),
        ('florida', 'gainesville'),
        ('florida', 'jacksonville'),
        ('florida', 'keys'),
        ('florida', 'lakecity'),
        ('florida', 'lakeland'),
        ('florida', 'miami', 'brw'),
        ('florida', 'miami', 'mdc'),
        ('florida', 'ocala'),
        ('florida', 'okaloosa'),
        ('florida', 'orlando'),
        ('florida', 'panamacity'),
        ('florida', 'pensacola'),
        ('florida', 'sarasota'),
        ('florida', 'spacecoast'),
        ('florida', 'staugustine'),
        ('florida', 'tallahassee'),
        ('florida', 'tampa', 'hdo'),
        ('florida', 'tampa', 'hil'),
        ('florida', 'tampa', 'pnl'),
        ('florida', 'tampa', 'psc'),
        ('florida', 'treasure'),
        ('georgia', 'albanyga'),
        ('georgia', 'athensga'),
        ('georgia', 'atlanta', 'atl'),
        ('georgia', 'atlanta', 'eat'),
        ('georgia', 'atlanta', 'nat'),
        ('georgia', 'atlanta', 'sat'),
        ('georgia', 'atlanta', 'wat'),
        ('georgia', 'augusta'),
        ('georgia', 'brunswick'),
        ('georgia', 'columbusga'),
        ('georgia', 'macon'),
        ('georgia', 'nwga'),
        ('georgia', 'savannah'),
        ('georgia', 'statesboro'),
        ('georgia', 'valdosta'),
        ('hawaii', 'honolulu'),
        ('idaho', 'boise'),
        ('idaho', 'eastidaho'),
        ('idaho', 'lewiston'),
        ('idaho', 'twinfalls'),
        ('illinois', 'bn'),
        ('illinois', 'carbondale'),
        ('illinois', 'chambana'),
        ('illinois', 'chicago', 'chc'),
        ('illinois', 'chicago', 'nch'),
        ('illinois', 'chicago', 'nwc'),
        ('illinois', 'chicago', 'nwi'),
        ('illinois', 'chicago', 'sox'),
        ('illinois', 'chicago', 'wcl'),
        ('illinois', 'decatur'),
        ('illinois', 'lasalle'),
        ('illinois', 'mattoon'),
        ('illinois', 'peoria'),
        ('illinois', 'quincy'),
        ('illinois', 'rockford'),
        ('illinois', 'springfieldil'),
        ('indiana', 'bloomington'),
        ('indiana', 'evansville'),
        ('indiana', 'fortwayne'),
        ('indiana', 'indianapolis'),
        ('indiana', 'kokomo'),
        ('indiana', 'muncie'),
        ('indiana', 'richmondin'),
        ('indiana', 'southbend'),
        ('indiana', 'terrehaute'),
        ('indiana', 'tippecanoe'),
        ('iowa', 'ames'),
        ('iowa', 'cedarrapids'),
        ('iowa', 'desmoines'),
        ('iowa', 'dubuque'),
        ('iowa', 'fortdodge'),
        ('iowa', 'iowacity'),
        ('iowa', 'masoncity'),
        ('iowa', 'ottumwa'),
        ('iowa', 'quadcities'),
        ('iowa', 'siouxcity'),
        ('iowa', 'waterloo'),
        ('kansas', 'ksu'),
        ('kansas', 'lawrence'),
        ('kansas', 'nwks'),
        ('kansas', 'salina'),
        ('kansas', 'seks'),
        ('kansas', 'swks'),
        ('kansas', 'topeka'),
        ('kansas', 'wichita'),
        ('kentucky', 'bgky'),
        ('kentucky', 'eastky'),
        ('kentucky', 'lexington'),
        ('kentucky', 'louisville'),
        ('kentucky', 'owensboro'),
        ('kentucky', 'westky'),
        ('louisiana', 'batonrouge'),
        ('louisiana', 'cenla'),
        ('louisiana', 'houma'),
        ('louisiana', 'lafayette'),
        ('louisiana', 'lakecharles'),
        ('louisiana', 'monroe'),
        ('louisiana', 'neworleans'),
        ('louisiana', 'shreveport'),
        ('maine', 'maine'),
        ('maryland', 'annapolis'),
        ('maryland', 'baltimore'),
        ('maryland', 'easternshore'),
        ('maryland', 'frederick'),
        ('maryland', 'smd'),
        ('maryland', 'westmd'),
        ('massachusetts', 'boston', 'bmw'),
        ('massachusetts', 'boston', 'gbs'),
        ('massachusetts', 'boston', 'nos'),
        ('massachusetts', 'boston', 'nwb'),
        ('massachusetts', 'boston', 'sob'),
        ('massachusetts', 'capecod'),
        ('massachusetts', 'southcoast'),
        ('massachusetts', 'westernmass'),
        ('massachusetts', 'worcester'),
        ('michigan', 'annarbor'),
        ('michigan', 'battlecreek'),
        ('michigan', 'centralmich'),
        ('michigan', 'detroit', 'mcb'),
        ('michigan', 'detroit', 'okl'),
        ('michigan', 'detroit', 'wyn'),
        ('michigan', 'flint'),
        ('michigan', 'grandrapids'),
        ('michigan', 'holland'),
        ('michigan', 'jxn'),
        ('michigan', 'kalamazoo'),
        ('michigan', 'lansing'),
        ('michigan', 'monroemi'),
        ('michigan', 'muskegon'),
        ('michigan', 'nmi'),
        ('michigan', 'porthuron'),
        ('michigan', 'saginaw'),
        ('michigan', 'swmi'),
        ('michigan', 'thumb'),
        ('michigan', 'up'),
        ('minnesota', 'bemidji'),
        ('minnesota', 'brainerd'),
        ('minnesota', 'duluth'),
        ('minnesota', 'mankato'),
        ('minnesota', 'marshall'),
        ('minnesota', 'minneapolis', 'ank'),
        ('minnesota', 'minneapolis', 'csw'),
        ('minnesota', 'minneapolis', 'dak'),
        ('minnesota', 'minneapolis', 'hnp'),
        ('minnesota', 'minneapolis', 'ram'),
        ('minnesota', 'minneapolis', 'wsh'),
        ('minnesota', 'rmn'),
        ('minnesota', 'stcloud'),
        ('mississippi', 'gulfport'),
        ('mississippi', 'hattiesburg'),
        ('mississippi', 'jackson'),
        ('mississippi', 'meridian'),
        ('mississippi', 'natchez'),
        ('mississippi', 'northmiss'),
        ('missouri', 'columbiamo'),
        ('missouri', 'joplin'),
        ('missouri', 'kansascity'),
        ('missouri', 'kirksville'),
        ('missouri', 'loz'),
        ('missouri', 'semo'),
        ('missouri', 'springfield'),
        ('missouri', 'stjoseph'),
        ('missouri', 'stlouis'),
        ('montana', 'billings'),
        ('montana', 'bozeman'),
        ('montana', 'butte'),
        ('montana', 'greatfalls'),
        ('montana', 'helena'),
        ('montana', 'kalispell'),
        ('montana', 'missoula'),
        ('montana', 'montana'),
        ('nebraska', 'grandisland'),
        ('nebraska', 'lincoln'),
        ('nebraska', 'northplatte'),
        ('nebraska', 'omaha'),
        ('nebraska', 'scottsbluff'),
        ('nevada', 'elko'),
        ('nevada', 'lasvegas'),
        ('nevada', 'reno'),
        ('new_hampshire', 'nh'),
        ('new_jersey', 'cnj'),
        ('new_jersey', 'jerseyshore'),
        ('new_jersey', 'newjersey'),
        ('new_jersey', 'southjersey'),
        ('new_mexico', 'albuquerque'),
        ('new_mexico', 'clovis'),
        ('new_mexico', 'farmington'),
        ('new_mexico', 'lascruces'),
        ('new_mexico', 'roswell'),
        ('new_mexico', 'santafe'),
        ('new_york', 'albany'),
        ('new_york', 'binghamton'),
        ('new_york', 'buffalo'),
        ('new_york', 'catskills'),
        ('new_york', 'chautauqua'),
        ('new_york', 'elmira'),
        ('new_york', 'fingerlakes'),
        ('new_york', 'glensfalls'),
        ('new_york', 'hudsonvalley'),
        ('new_york', 'ithaca'),
        ('new_york', 'longisland'),
        ('new_york', 'newyork', 'brk'),
        ('new_york', 'newyork', 'brx'),
        ('new_york', 'newyork', 'fct'),
        ('new_york', 'newyork', 'jsy'),
        ('new_york', 'newyork', 'lgi'),
        ('new_york', 'newyork', 'mnh'),
        ('new_york', 'newyork', 'que'),
        ('new_york', 'newyork', 'stn'),
        ('new_york', 'newyork', 'wch'),
        ('new_york', 'oneonta'),
        ('new_york', 'plattsburgh'),
        ('new_york', 'potsdam'),
        ('new_york', 'rochester'),
        ('new_york', 'syracuse'),
        ('new_york', 'twintiers'),
        ('new_york', 'utica'),
        ('new_york', 'watertown'),
        ('north_carolina', 'asheville'),
        ('north_carolina', 'boone'),
        ('north_carolina', 'charlotte'),
        ('north_carolina', 'eastnc'),
        ('north_carolina', 'fayetteville'),
        ('north_carolina', 'greensboro'),
        ('north_carolina', 'hickory'),
        ('north_carolina', 'onslow'),
        ('north_carolina', 'outerbanks'),
        ('north_carolina', 'raleigh'),
        ('north_carolina', 'wilmington'),
        ('north_carolina', 'winstonsalem'),
        ('north_dakota', 'bismarck'),
        ('north_dakota', 'fargo'),
        ('north_dakota', 'grandforks'),
        ('north_dakota', 'nd'),
        ('ohio', 'akroncanton'),
        ('ohio', 'ashtabula'),
        ('ohio', 'athensohio'),
        ('ohio', 'chillicothe'),
        ('ohio', 'cincinnati'),
        ('ohio', 'cleveland'),
        ('ohio', 'columbus'),
        ('ohio', 'dayton'),
        ('ohio', 'limaohio'),
        ('ohio', 'mansfield'),
        ('ohio', 'sandusky'),
        ('ohio', 'toledo'),
        ('ohio', 'tuscarawas'),
        ('ohio', 'youngstown'),
        ('ohio', 'zanesville'),
        ('oklahoma', 'enid'),
        ('oklahoma', 'lawton'),
        ('oklahoma', 'oklahomacity'),
        ('oklahoma', 'stillwater'),
        ('oklahoma', 'tulsa'),
        ('oregon', 'bend'),
        ('oregon', 'corvallis'),
        ('oregon', 'eastoregon'),
        ('oregon', 'eugene'),
        ('oregon', 'klamath'),
        ('oregon', 'medford'),
        ('oregon', 'oregoncoast'),
        ('oregon', 'portland', 'clc'),
        ('oregon', 'portland', 'clk'),
        ('oregon', 'portland', 'grg'),
        ('oregon', 'portland', 'mlt'),
        ('oregon', 'portland', 'nco'),
        ('oregon', 'portland', 'wsc'),
        ('oregon', 'portland', 'yam'),
        ('oregon', 'roseburg'),
        ('oregon', 'salem'),
        ('pennsylvania', 'allentown'),
        ('pennsylvania', 'altoona'),
        ('pennsylvania', 'chambersburg'),
        ('pennsylvania', 'erie'),
        ('pennsylvania', 'harrisburg'),
        ('pennsylvania', 'lancaster'),
        ('pennsylvania', 'meadville'),
        ('pennsylvania', 'pennstate'),
        ('pennsylvania', 'philadelphia'),
        ('pennsylvania', 'pittsburgh'),
        ('pennsylvania', 'poconos'),
        ('pennsylvania', 'reading'),
        ('pennsylvania', 'scranton'),
        ('pennsylvania', 'williamsport'),
        ('pennsylvania', 'york'),
        ('rhode_island', 'providence'),
        ('south_carolina', 'charleston'),
        ('south_carolina', 'columbia'),
        ('south_carolina', 'florencesc'),
        ('south_carolina', 'greenville'),
        ('south_carolina', 'hiltonhead'),
        ('south_carolina', 'myrtlebeach'),
        ('south_dakota', 'csd'),
        ('south_dakota', 'nesd'),
        ('south_dakota', 'rapidcity'),
        ('south_dakota', 'sd'),
        ('south_dakota', 'siouxfalls'),
        ('tennessee', 'chattanooga'),
        ('tennessee', 'clarksville'),
        ('tennessee', 'cookeville'),
        ('tennessee', 'jacksontn'),
        ('tennessee', 'knoxville'),
        ('tennessee', 'memphis'),
        ('tennessee', 'nashville'),
        ('tennessee', 'tricities'),
        ('texas', 'abilene'),
        ('texas', 'amarillo'),
        ('texas', 'austin'),
        ('texas', 'beaumont'),
        ('texas', 'bigbend'),
        ('texas', 'brownsville'),
        ('texas', 'collegestation'),
        ('texas', 'corpuschristi'),
        ('texas', 'dallas', 'dal'),
        ('texas', 'dallas', 'ftw'),
        ('texas', 'dallas', 'mdf'),
        ('texas', 'dallas', 'ndf'),
        ('texas', 'dallas', 'sdf'),
        ('texas', 'delrio'),
        ('texas', 'easttexas'),
        ('texas', 'elpaso'),
        ('texas', 'galveston'),
        ('texas', 'houston'),
        ('texas', 'killeen'),
        ('texas', 'laredo'),
        ('texas', 'lubbock'),
        ('texas', 'mcallen'),
        ('texas', 'nacogdoches'),
        ('texas', 'odessa'),
        ('texas', 'sanangelo'),
        ('texas', 'sanantonio'),
        ('texas', 'sanmarcos'),
        ('texas', 'texoma'),
        ('texas', 'victoriatx'),
        ('texas', 'waco'),
        ('texas', 'wichitafalls'),
        ('utah', 'logan'),
        ('utah', 'ogden'),
        ('utah', 'provo'),
        ('utah', 'saltlakecity'),
        ('utah', 'stgeorge'),
        ('vermont', 'vermont'),
        ('virginia', 'blacksburg'),
        ('virginia', 'charlottesville'),
        ('virginia', 'danville'),
        ('virginia', 'fredericksburg'),
        ('virginia', 'harrisonburg'),
        ('virginia', 'lynchburg'),
        ('virginia', 'norfolk'),
        ('virginia', 'richmond'),
        ('virginia', 'roanoke'),
        ('virginia', 'swva'),
        ('virginia', 'winchester'),
        ('washington', 'bellingham'),
        ('washington', 'kpr'),
        ('washington', 'moseslake'),
        ('washington', 'olympic'),
        ('washington', 'pullman'),
        ('washington', 'seattle', 'est'),
        ('washington', 'seattle', 'kit'),
        ('washington', 'seattle', 'oly'),
        ('washington', 'seattle', 'see'),
        ('washington', 'seattle', 'skc'),
        ('washington', 'seattle', 'sno'),
        ('washington', 'seattle', 'tac'),
        ('washington', 'skagit'),
        ('washington', 'spokane'),
        ('washington', 'wenatchee'),
        ('washington', 'yakima'),
        ('west_virginia', 'charlestonwv'),
        ('west_virginia', 'huntington'),
        ('west_virginia', 'martinsburg'),
        ('west_virginia', 'morgantown'),
        ('west_virginia', 'parkersburg'),
        ('west_virginia', 'swv'),
        ('west_virginia', 'wheeling'),
        ('west_virginia', 'wv'),
        ('wisconsin', 'appleton'),
        ('wisconsin', 'eauclaire'),
        ('wisconsin', 'greenbay'),
        ('wisconsin', 'janesville'),
        ('wisconsin', 'lacrosse'),
        ('wisconsin', 'madison'),
        ('wisconsin', 'milwaukee'),
        ('wisconsin', 'northernwi'),
        ('wisconsin', 'racine'),
        ('wisconsin', 'sheboygan'),
        ('wisconsin', 'wausau'),
        ('wyoming', 'wyoming')]

    canada = [('alberta', 'calgary'),
        ('alberta', 'edmonton'),
        ('alberta', 'ftmcmurray'),
        ('alberta', 'hat'),
        ('alberta', 'lethbridge'),
        ('alberta', 'peace'),
        ('alberta', 'reddeer'),
        ('british_columbia', 'abbotsford'),
        ('british_columbia', 'cariboo'),
        ('british_columbia', 'comoxvalley'),
        ('british_columbia', 'kamloops'),
        ('british_columbia', 'kelowna'),
        ('british_columbia', 'kootenays'),
        ('british_columbia', 'nanaimo'),
        ('british_columbia', 'princegeorge'),
        ('british_columbia', 'skeena'),
        ('british_columbia', 'sunshine'),
        ('british_columbia', 'vancouver', 'bnc'),
        ('british_columbia', 'vancouver', 'nvn'),
        ('british_columbia', 'vancouver', 'pml'),
        ('british_columbia', 'vancouver', 'rch'),
        ('british_columbia', 'vancouver', 'rds'),
        ('british_columbia', 'vancouver', 'van'),
        ('british_columbia', 'victoria'),
        ('british_columbia', 'whistler'),
        ('manitoba', 'winnipeg'),
        ('new_brunswick', 'newbrunswick'),
        ('newfoundland_and_labrador', 'newfoundland'),
        ('northwest_territories', 'territories'),
        ('northwest_territories', 'yellowknife'),
        ('nova_scotia', 'halifax'),
        ('ontario', 'barrie'),
        ('ontario', 'belleville'),
        ('ontario', 'brantford'),
        ('ontario', 'chatham'),
        ('ontario', 'cornwall'),
        ('ontario', 'guelph'),
        ('ontario', 'hamilton'),
        ('ontario', 'kingston'),
        ('ontario', 'kitchener'),
        ('ontario', 'londonon'),
        ('ontario', 'niagara'),
        ('ontario', 'ottawa'),
        ('ontario', 'owensound'),
        ('ontario', 'peterborough'),
        ('ontario', 'sarnia'),
        ('ontario', 'soo'),
        ('ontario', 'sudbury'),
        ('ontario', 'thunderbay'),
        ('ontario', 'toronto', 'bra'),
        ('ontario', 'toronto', 'drh'),
        ('ontario', 'toronto', 'mss'),
        ('ontario', 'toronto', 'oak'),
        ('ontario', 'toronto', 'tor'),
        ('ontario', 'toronto', 'yrk'),
        ('ontario', 'windsor'),
        ('prince_edward_island', 'pei'),
        ('quebec', 'montreal'),
        ('quebec', 'quebec'),
        ('quebec', 'saguenay'),
        ('quebec', 'sherbrooke'),
        ('quebec', 'troisrivieres'),
        ('saskatchewan', 'regina'),
        ('saskatchewan', 'saskatoon'),
        ('yukon_territory', 'whitehorse')]

    territories = [('territories', 'micronesia'),
        ('territories', 'puertorico'),
        ('territories', 'virgin')]

    austria = [('austria', 'vienna')]

    blegium = [('belgium', 'brussels')]

    bulgaria = [('bulgaria', 'bulgaria')]

    croatia = [('croatia', 'zagreb')]

    czech_republic = [('czech_republic', 'prague')]

    denmar = [('denmark', 'copenhagen')]

    finland = [('finland', 'helsinki')]

    france = [('france', 'bordeaux'),
        ('france', 'cotedazur'),
        ('france', 'grenoble'),
        ('france', 'lille'),
        ('france', 'loire'),
        ('france', 'lyon'),
        ('france', 'marseilles'),
        ('france', 'montpellier'),
        ('france', 'paris'),
        ('france', 'rennes'),
        ('france', 'rouen'),
        ('france', 'strasbourg'),
        ('france', 'toulouse')]

    germany = [('germany', 'berlin'),
        ('germany', 'bremen'),
        ('germany', 'cologne'),
        ('germany', 'dresden'),
        ('germany', 'dusseldorf'),
        ('germany', 'essen'),
        ('germany', 'frankfurt'),
        ('germany', 'hamburg'),
        ('germany', 'hannover'),
        ('germany', 'heidelberg'),
        ('germany', 'kaiserslautern'),
        ('germany', 'leipzig'),
        ('germany', 'munich'),
        ('germany', 'nuremberg'),
        ('germany', 'stuttgart')]

    greece = [('greece', 'athens')]

    hungary = [('hungary', 'budapest')]

    iceland = [('iceland', 'reykjavik')]

    ireland = [('ireland', 'dublin')]

    italy = [('italy', 'bologna'),
        ('italy', 'florence'),
        ('italy', 'genoa'),
        ('italy', 'milan'),
        ('italy', 'naples'),
        ('italy', 'perugia'),
        ('italy', 'rome'),
        ('italy', 'sardinia'),
        ('italy', 'sicily'),
        ('italy', 'torino'),
        ('italy', 'venice')]

    luxembourg = [('luxembourg', 'luxembourg')]

    netherlands = [('netherlands', 'amsterdam')]
    
    norway = [('norway', 'oslo')]
    
    poland = [('poland', 'warsaw')]

    portugal = [('portugal', 'faro'), ('portugal', 'lisbon'), ('portugal', 'porto')]
    
    romania = [('romania', 'bucharest')]

    russia = [('russian_federation', 'stpetersburg'), ('russian_federation', 'moscow')]

    spain = [('spain', 'alicante'),
        ('spain', 'baleares'),
        ('spain', 'barcelona'),
        ('spain', 'bilbao'),
        ('spain', 'cadiz'),
        ('spain', 'canarias'),
        ('spain', 'granada'),
        ('spain', 'madrid'),
        ('spain', 'malaga'),
        ('spain', 'sevilla'),
        ('spain', 'valencia')]
        
    sweden = [('sweden', 'stockholm')]
    
    switzerland = [('switzerland', 'basel'),
        ('switzerland', 'bern'),
        ('switzerland', 'geneva'),
        ('switzerland', 'lausanne'),
        ('switzerland', 'zurich')]
        
    turkey = [('turkey', 'istanbul')]
    
    ukraine = [('ukraine', 'ukraine')]
    
    united_kingdom = [('united_kingdom', 'aberdeen'),
        ('united_kingdom', 'bath'),
        ('united_kingdom', 'belfast'),
        ('united_kingdom', 'birmingham'),
        ('united_kingdom', 'brighton'),
        ('united_kingdom', 'bristol'),
        ('united_kingdom', 'cambridge'),
        ('united_kingdom', 'cardiff'),
        ('united_kingdom', 'coventry'),
        ('united_kingdom', 'derby'),
        ('united_kingdom', 'devon'),
        ('united_kingdom', 'dundee'),
        ('united_kingdom', 'eastmids'),
        ('united_kingdom', 'edinburgh'),
        ('united_kingdom', 'essex'),
        ('united_kingdom', 'glasgow'),
        ('united_kingdom', 'hampshire'),
        ('united_kingdom', 'kent'),
        ('united_kingdom', 'leeds'),
        ('united_kingdom', 'liverpool'),
        ('united_kingdom', 'london'),
        ('united_kingdom', 'manchester'),
        ('united_kingdom', 'newcastle'),
        ('united_kingdom', 'norwich'),
        ('united_kingdom', 'nottingham'),
        ('united_kingdom', 'oxford'),
        ('united_kingdom', 'sheffield')]
        
    bangladesh = [('bangladesh', 'bangladesh')]
    
    china = [('china', 'beijing'),
        ('china', 'chengdu'),
        ('china', 'chongqing'),
        ('china', 'dalian'),
        ('china', 'guangzhou'),
        ('china', 'hangzhou'),
        ('china', 'nanjing'),
        ('china', 'shanghai'),
        ('china', 'shenyang'),
        ('china', 'shenzhen'),
        ('china', 'wuhan'),
        ('china', 'xian')]
        
    guam_micronesia = [('guam_micronesia', 'micronesia')]

    hong_kong = [('hong_kong', 'hongkong')]
    
    india = [('india', 'ahmedabad'),
        ('india', 'bangalore'),
        ('india', 'bhubaneswar'),
        ('india', 'chandigarh'),
        ('india', 'chennai'),
        ('india', 'delhi'),
        ('india', 'goa'),
        ('india', 'hyderabad'),
        ('india', 'indore'),
        ('india', 'jaipur'),
        ('india', 'kerala'),
        ('india', 'kolkata'),
        ('india', 'lucknow'),
        ('india', 'mumbai'),
        ('india', 'pune'),
        ('india', 'surat')]
        
    indonesia = [('indonesia', 'jakarta')]
    
    iran = [('iran', 'tehran')]

    iraq = [('iraq', 'baghdad')]
    
    israel_and_palestine = [('israel_and_palestine', 'haifa'),
        ('israel_and_palestine', 'jerusalem'),
        ('israel_and_palestine', 'ramallah'),
        ('israel_and_palestine', 'telaviv')]

    japan = [('japan', 'fukuoka'),
        ('japan', 'hiroshima'),
        ('japan', 'nagoya'),
        ('japan', 'okinawa'),
        ('japan', 'osaka'),
        ('japan', 'sapporo'),
        ('japan', 'sendai'),
        ('japan', 'tokyo')]

    korea = [('korea', 'seoul')]
    
    kuwait = [('kuwait', 'kuwait')]
    
    lebanon = [('lebanon', 'beirut')]
    
    malaysia = [('malaysia', 'malaysia')]
    
    pakistan = [('pakistan', 'pakistan')]
    
    philippines = [('philippines', 'bacolod'),
        ('philippines', 'cdo'),
        ('philippines', 'cebu'),
        ('philippines', 'davaocity'),
        ('philippines', 'iloilo'),
        ('philippines', 'manila'),
        ('philippines', 'naga'),
        ('philippines', 'pampanga'),
        ('philippines', 'zamboanga')]

    singapore = [('singapore', 'singapore')]

    taiwan = [('taiwan', 'taipei')]

    thailand = [('thailand', 'bangkok')]
    
    united_arab_emirates = [('united_arab_emirates', 'dubai')]
    
    vietnam = [('vietnam', 'vietnam')]
    
    austria = [('australia', 'adelaide'),
        ('australia', 'brisbane'),
        ('australia', 'cairns'),
        ('australia', 'canberra'),
        ('australia', 'darwin'),
        ('australia', 'goldcoast'),
        ('australia', 'hobart'),
        ('australia', 'melbourne'),
        ('australia', 'ntl'),
        ('australia', 'perth'),
        ('australia', 'sydney'),
        ('australia', 'wollongong')]
        
    new_zealand = [('new_zealand', 'auckland'),
        ('new_zealand', 'christchurch'),
        ('new_zealand', 'dunedin'),
        ('new_zealand', 'wellington')]
        
    argentina = [('argentina', 'buenosaires')]
    
    bolivia = [('bolivia', 'lapaz')]
    
    brazil = [('brazil', 'belohorizonte'),
        ('brazil', 'brasilia'),
        ('brazil', 'curitiba'),
        ('brazil', 'fortaleza'),
        ('brazil', 'portoalegre'),
        ('brazil', 'recife'),
        ('brazil', 'rio'),
        ('brazil', 'salvador'),
        ('brazil', 'saopaulo')]

    caribbean_islands = [('caribbean_islands', 'caribbean')]

    chile = [('chile', 'santiago')]

    colombia = [('colombia', 'colombia')]

    costa_rica = [('costa_rica', 'costarica')]

    dominican_republic = [('dominican_republic', 'santodomingo')]

    ecuador = [('ecuador', 'quito')]

    el_salvador = [('el_salvador', 'elsalvador')]

    guatemala = [('guatemala', 'guatemala')]

    mexico = [('mexico', 'yucatan'),
        ('mexico', 'acapulco'),
        ('mexico', 'puebla'),
        ('mexico', 'oaxaca'),
        ('mexico', 'pv'),
        ('mexico', 'chihuahua'),
        ('mexico', 'veracruz'),
        ('mexico', 'guanajuato'),
        ('mexico', 'tijuana'), 
        ('mexico', 'mazatlan'),
        ('mexico', 'guadalajara'),
        ('mexico', 'monterrey'),
        ('mexico', 'bajasur'),
        ('mexico', 'mexicocity'),
        ('mexico', 'hermosillo'),
        ('mexico', 'juarez')]

    nicaragua = [('nicaragua', 'managua')]

    panama = [('panama', 'panama')]

    peru = [('peru', 'lima')]

    puerto_rico = [('puerto_rico', 'puertorico')]

    uruguay = [('uruguay', 'montevideo')]

    venezuela = [('venezuela', 'caracas')]

    virgin_islands_us = [('virgin_islands_us', 'virgin')]

    egypt = [('egypt', 'cairo')]

    ethiopia = [('ethiopia', 'addisababa')]

    ghana = [('ghana', 'accra')]

    kenya = [('kenya', 'kenya')]

    morocco = [('morocco', 'casablanca')]

    south_africa = [('south_africa', 'johannesburg'),
        ('south_africa', 'pretoria'),
        ('south_africa', 'durban'),
        ('south_africa', 'capetown')]

    tunisia = [('tunisia', 'tunis')]