class Search:
    continental_us = [('alabama', 'auburn'),
        ('alabama', 'bham'),
        ('alabama', 'columbusga'),
        ('alabama', 'dothan'),
        ('alabama', 'gadsden'),
        ('alabama', 'huntsville'),
        ('alabama', 'mobile'),
        ('alabama', 'montgomery'),
        ('alabama', 'shoals'),
        ('alabama', 'tuscaloosa'),
        ('arizona', 'flagstaff'),
        ('arizona', 'mohave'),
        ('arizona', 'phoenix'),
        ('arizona', 'prescott'),
        ('arizona', 'showlow'),
        ('arizona', 'sierravista'),
        ('arizona', 'tucson'),
        ('arizona', 'yuma'),
        ('arkansas', 'fayar'),
        ('arkansas', 'fortsmith'),
        ('arkansas', 'jonesboro'),
        ('arkansas', 'littlerock'),
        ('arkansas', 'memphis'),
        ('arkansas', 'texarkana'),
        ('california', 'bakersfield'),
        ('california', 'chico'),
        ('california', 'fresno'),
        ('california', 'goldcountry'),
        ('california', 'hanford'),
        ('california', 'humboldt'),
        ('california', 'imperial'),
        ('california', 'inlandempire'),
        ('california', 'losangeles', 'ant'),
        ('california', 'losangeles', 'lac'),
        ('california', 'losangeles', 'lgb'),
        ('california', 'losangeles', 'sfv'),
        ('california', 'losangeles', 'sgv'),
        ('california', 'losangeles', 'wst'),
        ('california', 'mendocino'),
        ('california', 'merced'),
        ('california', 'modesto'),
        ('california', 'monterey'),
        ('california', 'orangecounty'),
        ('california', 'palmsprings'),
        ('california', 'redding'),
        ('california', 'reno'),
        ('california', 'sacramento'),
        ('california', 'sandiego', 'csd'),
        ('california', 'sandiego', 'esd'),
        ('california', 'sandiego', 'nsd'),
        ('california', 'sandiego', 'ssd'),
        ('california', 'santabarbara'),
        ('california', 'santamaria'),
        ('california', 'sfbay', 'eby'),
        ('california', 'sfbay', 'nby'),
        ('california', 'sfbay', 'pen'),
        ('california', 'sfbay', 'sby'),
        ('california', 'sfbay', 'scz'),
        ('california', 'sfbay', 'sfc'),
        ('california', 'siskiyou'),
        ('california', 'slo'),
        ('california', 'stockton'),
        ('california', 'susanville'),
        ('california', 'ventura'),
        ('california', 'visalia'),
        ('california', 'yubasutter'),
        ('colorado', 'boulder'),
        ('colorado', 'cosprings'),
        ('colorado', 'denver'),
        ('colorado', 'eastco'),
        ('colorado', 'fortcollins'),
        ('colorado', 'pueblo'),
        ('colorado', 'rockies'),
        ('colorado', 'westslope'),
        ('connecticut', 'hartford'),
        ('connecticut', 'newhaven'),
        ('connecticut', 'newlondon'),
        ('connecticut', 'newyork', 'fct'),
        ('connecticut', 'nwct'),
        ('delaware', 'delaware'),
        ('district_of_columbia', 'washingtondc'),
        ('florida', 'cfl'),
        ('florida', 'daytona'),
        ('florida', 'fortmyers', 'chl'),
        ('florida', 'fortmyers', 'col'),
        ('florida', 'fortmyers', 'lee'),
        ('florida', 'gadsden'),
        ('florida', 'gainesville'),
        ('florida', 'jacksonville'),
        ('florida', 'keys'),
        ('florida', 'lakecity'),
        ('florida', 'lakeland'),
        ('florida', 'miami', 'brw'),
        ('florida', 'miami', 'mdc'),
        ('florida', 'miami', 'pbc'),
        ('florida', 'ocala'),
        ('florida', 'okaloosa'),
        ('florida', 'orlando'),
        ('florida', 'panamacity'),
        ('florida', 'pensacola'),
        ('florida', 'sarasota'),
        ('florida', 'spacecoast'),
        ('florida', 'staugustine'),
        ('florida', 'tallahassee'),
        ('florida', 'tampa', 'hdo'),
        ('florida', 'tampa', 'hil'),
        ('florida', 'tampa', 'pnl'),
        ('florida', 'tampa', 'psc'),
        ('florida', 'treasure'),
        ('georgia', 'albanyga'),
        ('georgia', 'athensga'),
        ('georgia', 'atlanta', 'atl'),
        ('georgia', 'atlanta', 'eat'),
        ('georgia', 'atlanta', 'nat'),
        ('georgia', 'atlanta', 'sat'),
        ('georgia', 'atlanta', 'wat'),
        ('georgia', 'augusta'),
        ('georgia', 'brunswick'),
        ('georgia', 'columbusga'),
        ('georgia', 'macon'),
        ('georgia', 'nwga'),
        ('georgia', 'savannah'),
        ('georgia', 'statesboro'),
        ('georgia', 'valdosta'),
        ('idaho', 'boise'),
        ('idaho', 'eastidaho'),
        ('idaho', 'lewiston'),
        ('idaho', 'pullman'),
        ('idaho', 'spokane'),
        ('idaho', 'twinfalls'),
        ('illinois', 'bn'),
        ('illinois', 'carbondale'),
        ('illinois', 'chambana'),
        ('illinois', 'chicago', 'chc'),
        ('illinois', 'chicago', 'nch'),
        ('illinois', 'chicago', 'nwc'),
        ('illinois', 'chicago', 'nwi'),
        ('illinois', 'chicago', 'sox'),
        ('illinois', 'chicago', 'wcl'),
        ('illinois', 'decatur'),
        ('illinois', 'lasalle'),
        ('illinois', 'mattoon'),
        ('illinois', 'peoria'),
        ('illinois', 'quadcities'),
        ('illinois', 'quincy'),
        ('illinois', 'rockford'),
        ('illinois', 'springfieldil'),
        ('illinois', 'stlouis'),
        ('indiana', 'bloomington'),
        ('indiana', 'chicago', 'nwi'),
        ('indiana', 'evansville'),
        ('indiana', 'fortwayne'),
        ('indiana', 'indianapolis'),
        ('indiana', 'kokomo'),
        ('indiana', 'muncie'),
        ('indiana', 'richmondin'),
        ('indiana', 'southbend'),
        ('indiana', 'terrehaute'),
        ('indiana', 'tippecanoe'),
        ('iowa', 'ames'),
        ('iowa', 'cedarrapids'),
        ('iowa', 'desmoines'),
        ('iowa', 'dubuque'),
        ('iowa', 'fortdodge'),
        ('iowa', 'iowacity'),
        ('iowa', 'masoncity'),
        ('iowa', 'omaha'),
        ('iowa', 'ottumwa'),
        ('iowa', 'quadcities'),
        ('iowa', 'siouxcity'),
        ('iowa', 'waterloo'),
        ('kansas', 'kansascity'),
        ('kansas', 'ksu'),
        ('kansas', 'lawrence'),
        ('kansas', 'nwks'),
        ('kansas', 'salina'),
        ('kansas', 'seks'),
        ('kansas', 'swks'),
        ('kansas', 'topeka'),
        ('kansas', 'wichita'),
        ('kentucky', 'bgky'),
        ('kentucky', 'cincinnati'),
        ('kentucky', 'eastky'),
        ('kentucky', 'huntington'),
        ('kentucky', 'lexington'),
        ('kentucky', 'louisville'),
        ('kentucky', 'owensboro'),
        ('kentucky', 'westky'),
        ('louisiana', 'batonrouge'),
        ('louisiana', 'cenla'),
        ('louisiana', 'houma'),
        ('louisiana', 'lafayette'),
        ('louisiana', 'lakecharles'),
        ('louisiana', 'monroe'),
        ('louisiana', 'neworleans'),
        ('louisiana', 'shreveport'),
        ('maine', 'maine'),
        ('maryland', 'annapolis'),
        ('maryland', 'baltimore'),
        ('maryland', 'chambersburg'),
        ('maryland', 'easternshore'),
        ('maryland', 'frederick'),
        ('maryland', 'smd'),
        ('maryland', 'washingtondc'),
        ('maryland', 'westmd'),
        ('massachusetts', 'boston', 'bmw'),
        ('massachusetts', 'boston', 'gbs'),
        ('massachusetts', 'boston', 'nos'),
        ('massachusetts', 'boston', 'nwb'),
        ('massachusetts', 'boston', 'sob'),
        ('massachusetts', 'capecod'),
        ('massachusetts', 'southcoast'),
        ('massachusetts', 'westernmass'),
        ('massachusetts', 'worcester'),
        ('michigan', 'annarbor'),
        ('michigan', 'battlecreek'),
        ('michigan', 'centralmich'),
        ('michigan', 'detroit', 'mcb'),
        ('michigan', 'detroit', 'okl'),
        ('michigan', 'detroit', 'wyn'),
        ('michigan', 'flint'),
        ('michigan', 'grandrapids'),
        ('michigan', 'holland'),
        ('michigan', 'jxn'),
        ('michigan', 'kalamazoo'),
        ('michigan', 'lansing'),
        ('michigan', 'monroemi'),
        ('michigan', 'muskegon'),
        ('michigan', 'nmi'),
        ('michigan', 'porthuron'),
        ('michigan', 'saginaw'),
        ('michigan', 'swmi'),
        ('michigan', 'thumb'),
        ('michigan', 'up'),
        ('minnesota', 'bemidji'),
        ('minnesota', 'brainerd'),
        ('minnesota', 'duluth'),
        ('minnesota', 'fargo'),
        ('minnesota', 'mankato'),
        ('minnesota', 'marshall'),
        ('minnesota', 'minneapolis', 'ank'),
        ('minnesota', 'minneapolis', 'csw'),
        ('minnesota', 'minneapolis', 'dak'),
        ('minnesota', 'minneapolis', 'hnp'),
        ('minnesota', 'minneapolis', 'ram'),
        ('minnesota', 'minneapolis', 'wsh'),
        ('minnesota', 'rmn'),
        ('minnesota', 'stcloud'),
        ('mississippi', 'gulfport'),
        ('mississippi', 'hattiesburg'),
        ('mississippi', 'jackson'),
        ('mississippi', 'memphis'),
        ('mississippi', 'meridian'),
        ('mississippi', 'natchez'),
        ('mississippi', 'northmiss'),
        ('missouri', 'columbiamo'),
        ('missouri', 'joplin'),
        ('missouri', 'kansascity'),
        ('missouri', 'kirksville'),
        ('missouri', 'loz'),
        ('missouri', 'semo'),
        ('missouri', 'springfield'),
        ('missouri', 'stjoseph'),
        ('missouri', 'stlouis'),
        ('montana', 'billings'),
        ('montana', 'bozeman'),
        ('montana', 'butte'),
        ('montana', 'greatfalls'),
        ('montana', 'helena'),
        ('montana', 'kalispell'),
        ('montana', 'missoula'),
        ('montana', 'montana'),
        ('nebraska', 'grandisland'),
        ('nebraska', 'lincoln'),
        ('nebraska', 'northplatte'),
        ('nebraska', 'omaha'),
        ('nebraska', 'scottsbluff'),
        ('nebraska', 'siouxcity'),
        ('nevada', 'elko'),
        ('nevada', 'lasvegas'),
        ('nevada', 'reno'),
        ('new_hampshire', 'nh'),
        ('new_jersey', 'cnj'),
        ('new_jersey', 'jerseyshore'),
        ('new_jersey', 'newjersey'),
        ('new_jersey', 'newyork', 'jsy'),
        ('new_jersey', 'southjersey'),
        ('new_mexico', 'albuquerque'),
        ('new_mexico', 'clovis'),
        ('new_mexico', 'farmington'),
        ('new_mexico', 'lascruces'),
        ('new_mexico', 'roswell'),
        ('new_mexico', 'santafe'),
        ('new_york', 'albany'),
        ('new_york', 'binghamton'),
        ('new_york', 'buffalo'),
        ('new_york', 'catskills'),
        ('new_york', 'chautauqua'),
        ('new_york', 'elmira'),
        ('new_york', 'fingerlakes'),
        ('new_york', 'glensfalls'),
        ('new_york', 'hudsonvalley'),
        ('new_york', 'ithaca'),
        ('new_york', 'longisland'),
        ('new_york', 'newyork', 'brk'),
        ('new_york', 'newyork', 'brx'),
        ('new_york', 'newyork', 'fct'),
        ('new_york', 'newyork', 'jsy'),
        ('new_york', 'newyork', 'lgi'),
        ('new_york', 'newyork', 'mnh'),
        ('new_york', 'newyork', 'que'),
        ('new_york', 'newyork', 'stn'),
        ('new_york', 'newyork', 'wch'),
        ('new_york', 'oneonta'),
        ('new_york', 'plattsburgh'),
        ('new_york', 'potsdam'),
        ('new_york', 'rochester'),
        ('new_york', 'syracuse'),
        ('new_york', 'twintiers'),
        ('new_york', 'utica'),
        ('new_york', 'watertown'),
        ('north_carolina', 'asheville'),
        ('north_carolina', 'boone'),
        ('north_carolina', 'charlotte'),
        ('north_carolina', 'eastnc'),
        ('north_carolina', 'fayetteville'),
        ('north_carolina', 'greensboro'),
        ('north_carolina', 'hickory'),
        ('north_carolina', 'onslow'),
        ('north_carolina', 'outerbanks'),
        ('north_carolina', 'raleigh'),
        ('north_carolina', 'wilmington'),
        ('north_carolina', 'winstonsalem'),
        ('north_dakota', 'bismarck'),
        ('north_dakota', 'fargo'),
        ('north_dakota', 'grandforks'),
        ('north_dakota', 'minneapolis'),
        ('north_dakota', 'nd'),
        ('ohio', 'akroncanton'),
        ('ohio', 'ashtabula'),
        ('ohio', 'athensohio'),
        ('ohio', 'chillicothe'),
        ('ohio', 'cincinnati'),
        ('ohio', 'cleveland'),
        ('ohio', 'columbus'),
        ('ohio', 'dayton'),
        ('ohio', 'huntington'),
        ('ohio', 'limaohio'),
        ('ohio', 'mansfield'),
        ('ohio', 'parkersburg'),
        ('ohio', 'sandusky'),
        ('ohio', 'toledo'),
        ('ohio', 'tuscarawas'),
        ('ohio', 'wheeling'),
        ('ohio', 'youngstown'),
        ('ohio', 'zanesville'),
        ('oklahoma', 'fortsmith'),
        ('oklahoma', 'lawton'),
        ('oklahoma', 'nwks'),
        ('oklahoma', 'oklahomacity'),
        ('oklahoma', 'stillwater'),
        ('oklahoma', 'texoma'),
        ('oklahoma', 'tulsa'),
        ('oregon', 'bend'),
        ('oregon', 'corvallis'),
        ('oregon', 'eastoregon'),
        ('oregon', 'eugene'),
        ('oregon', 'klamath'),
        ('oregon', 'medford'),
        ('oregon', 'oregoncoast'),
        ('oregon', 'portland', 'clc'),
        ('oregon', 'portland', 'clk'),
        ('oregon', 'portland', 'grg'),
        ('oregon', 'portland', 'mlt'),
        ('oregon', 'portland', 'nco'),
        ('oregon', 'portland', 'wsc'),
        ('oregon', 'portland', 'yam'),
        ('oregon', 'roseburg'),
        ('oregon', 'salem'),
        ('pennsylvania', 'allentown'),
        ('pennsylvania', 'altoona'),
        ('pennsylvania', 'chambersburg'),
        ('pennsylvania', 'erie'),
        ('pennsylvania', 'harrisburg'),
        ('pennsylvania', 'lancaster'),
        ('pennsylvania', 'meadville'),
        ('pennsylvania', 'pennstate'),
        ('pennsylvania', 'philadelphia'),
        ('pennsylvania', 'pittsburgh'),
        ('pennsylvania', 'poconos'),
        ('pennsylvania', 'reading'),
        ('pennsylvania', 'scranton'),
        ('pennsylvania', 'twintiers'),
        ('pennsylvania', 'williamsport'),
        ('pennsylvania', 'york'),
        ('rhode_island', 'providence'),
        ('south_carolina', 'charleston'),
        ('south_carolina', 'columbia'),
        ('south_carolina', 'florencesc'),
        ('south_carolina', 'greenville'),
        ('south_carolina', 'hiltonhead'),
        ('south_carolina', 'myrtlebeach'),
        ('south_dakota', 'csd'),
        ('south_dakota', 'nd'),
        ('south_dakota', 'nesd'),
        ('south_dakota', 'rapidcity'),
        ('south_dakota', 'sd'),
        ('south_dakota', 'siouxfalls'),
        ('tennessee', 'chattanooga'),
        ('tennessee', 'clarksville'),
        ('tennessee', 'cookeville'),
        ('tennessee', 'jacksontn'),
        ('tennessee', 'knoxville'),
        ('tennessee', 'memphis'),
        ('tennessee', 'nashville'),
        ('tennessee', 'tricities'),
        ('texas', 'abilene'),
        ('texas', 'amarillo'),
        ('texas', 'austin'),
        ('texas', 'beaumont'),
        ('texas', 'bigbend'),
        ('texas', 'brownsville'),
        ('texas', 'collegestation'),
        ('texas', 'corpuschristi'),
        ('texas', 'dallas', 'dal'),
        ('texas', 'dallas', 'ftw'),
        ('texas', 'dallas', 'mdf'),
        ('texas', 'dallas', 'ndf'),
        ('texas', 'dallas', 'sdf'),
        ('texas', 'delrio'),
        ('texas', 'easttexas'),
        ('texas', 'elpaso'),
        ('texas', 'galveston'),
        ('texas', 'houston'),
        ('texas', 'killeen'),
        ('texas', 'laredo'),
        ('texas', 'lubbock'),
        ('texas', 'mcallen'),
        ('texas', 'nacogdoches'),
        ('texas', 'odessa'),
        ('texas', 'sanangelo'),
        ('texas', 'sanantonio'),
        ('texas', 'sanmarcos'),
        ('texas', 'texarkana'),
        ('texas', 'texoma'),
        ('texas', 'victoriatx'),
        ('texas', 'waco'),
        ('texas', 'wichitafalls'),
        ('utah', 'logan'),
        ('utah', 'ogden'),
        ('utah', 'provo'),
        ('utah', 'saltlakecity'),
        ('utah', 'stgeorge'),
        ('vermont', 'vermont'),
        ('virginia', 'blacksburg'),
        ('virginia', 'charlottesville'),
        ('virginia', 'danville'),
        ('virginia', 'easternshore'),
        ('virginia', 'fredericksburg'),
        ('virginia', 'harrisonburg'),
        ('virginia', 'lynchburg'),
        ('virginia', 'norfolk'),
        ('virginia', 'richmond'),
        ('virginia', 'roanoke'),
        ('virginia', 'swva'),
        ('virginia', 'washingtondc'),
        ('virginia', 'winchester'),
        ('washington', 'bellingham'),
        ('washington', 'kpr'),
        ('washington', 'lewiston'),
        ('washington', 'moseslake'),
        ('washington', 'olympic'),
        ('washington', 'portland', 'clc'),
        ('washington', 'portland', 'clk'),
        ('washington', 'portland', 'grg'),
        ('washington', 'portland', 'mlt'),
        ('washington', 'portland', 'nco'),
        ('washington', 'portland', 'wsc'),
        ('washington', 'portland', 'yam'),
        ('washington', 'pullman'),
        ('washington', 'seattle', 'est'),
        ('washington', 'seattle', 'kit'),
        ('washington', 'seattle', 'oly'),
        ('washington', 'seattle', 'see'),
        ('washington', 'seattle', 'skc'),
        ('washington', 'seattle', 'sno'),
        ('washington', 'seattle', 'tac'),
        ('washington', 'skagit'),
        ('washington', 'spokane'),
        ('washington', 'wenatchee'),
        ('washington', 'yakima'),
        ('west_virginia', 'charlestonwv'),
        ('west_virginia', 'huntington'),
        ('west_virginia', 'martinsburg'),
        ('west_virginia', 'morgantown'),
        ('west_virginia', 'parkersburg'),
        ('west_virginia', 'swv'),
        ('west_virginia', 'wheeling'),
        ('west_virginia', 'wv'),
        ('wisconsin', 'appleton'),
        ('wisconsin', 'duluth'),
        ('wisconsin', 'eauclaire'),
        ('wisconsin', 'greenbay'),
        ('wisconsin', 'janesville'),
        ('wisconsin', 'lacrosse'),
        ('wisconsin', 'madison'),
        ('wisconsin', 'milwaukee'),
        ('wisconsin', 'northernwi'),
        ('wisconsin', 'racine'),
        ('wisconsin', 'sheboygan'),
        ('wisconsin', 'wausau'),
        ('wyoming', 'wyoming')]